### ISSUE TITLE
sourcemaps and breakpoints in IDE impossible?

### ISSUE THREAD

**Issue by eavichay** [aruntk/wc-loader#11]

**Comment by aruntk** [comment]
I think you'll be able to enable sourcemap if you use 

```js
//webpack.config.js
...
devtool: 'eval-source-map'
```

https://github.com/aruntk/polymer-webpack-demo/blob/master/webpack.config.js#L51

Sources tab in devtools

<img width="1280" alt="screen shot 2017-02-24 at 11 07 56 am" src="https://cloud.githubusercontent.com/assets/6007432/23291887/892a69a6-fa81-11e6-93ae-f991bcfa819d.png">

**Comment by aruntk** [comment]
@eavichay Closing the issue.
