### ISSUE TITLE
Does not work for AppLocalizeBehavior

### ISSUE THREAD

**Issue by emrass** [aruntk/wc-loader#12]
Hi, I tried wc-loader for one of my projects and stumbled upon an issue with AppLocalizeBehavior. If I have a Polymer component that references app-localize-behavior, then my application breaks with the following console error:

```
Uncaught ReferenceError: IntlMessageFormat is not defined
```

In another application, the error is a bit different, but seems to boil down to the same core issue (I have not found out, yet, what causes the different error message here):

```
Uncaught TypeError: Cannot set property 'IntlMessageFormat' of undefined
```

I have set up an example application based on the wc-loader demo app: https://github.com/emrass/polymer-webpack-demo

[app-localize-behavior.html](https://github.com/PolymerElements/app-localize-behavior/blob/master/app-localize-behavior.html) links a minified js file of the intl package. This is translated to a

```
require('../intl-messageformat/dist/intl-messageformat.min.js');
```

by wc-loader. From here on, I'm lost and don't know what causes the issue. I'll try to dig deeper, but would love to get your insights into the issue. Thanks!

**Comment by emrass** [comment]
Ps: After temporarily removing app-localize-behavior from my application, I received a similar issue from another library (same setup: a dependency Polymer component links an external lib js file). So the problem does not seem to be limited to AppLocalizeBehavior.

**Comment by emrass** [comment]
Digging deeper, this might be caused by intl-messageformat defining an IIFE that is called like [this](https://github.com/yahoo/intl-messageformat/blob/d361003c242edff921b0bcf540a1da133cca93f5/dist/intl-messageformat.js#L1872h):

```javascript
(function() {
  // code here
}).call(this);
```

After running through wc-loader, this comes out as:

```javascript
(function() {
  // code here
}).call(undefined);
```

**Comment by emrass** [comment]
Just to confirm this seems to be the root cause, I found that paper-menu-button relies on (dependency chain following): iron-dropdown -> opaque-animation -> web-animations -> web-animations-next-lite.min.js.

[web-animations-next-lite.min.js](https://rawgit.com/web-animations/web-animations-js/master/web-animations-next-lite.min.js) raises a related issue: `Uncaught TypeError: Cannot set property 'true' of undefined`. The reason seems to be that web-animations-next-lite.min.js defines a function which is immediately invoked at the very end of the file:

```javascript
function(a,b){/* ... */}({},function(){return this}())
```

Here, `this` is supposed to be `window`, but is `undefined` in the context of the wc-loader-bundled webpack file.

**Comment by emrass** [comment]
Update: this is likely caused by external files (those in bower_components or node_modules) being run through babel-loader. Without applying babel-loader to these files, it seems to work fine. I need to work a little more on that, but if this can be confirmed, this issue can be closed.

**Comment by emrass** [comment]
This issue was due to external dependencies being babelified. This issue can be closed. If you're stumbling upon the same issue - this is how I solved it:

**webpack.config.js**
```javascript
/* ... */
    module: {
        rules: [{
            test: /\.html$/,
            use: [
                'babel-loader?presets[]=es2015',
                'wc-loader'
            ],
            exclude: /(node_modules|bower_components)/
        }, {
            test: /\.html$/,
            use: 'wc-loader',
            include: /(node_modules|bower_components)/
        }, { /* ... */ }],
    },
/* ... */
```

**Comment by camargo** [comment]
@emrass This is still an issue for me even after the workaround you mentioned. Do you have any other ideas on how to fix this? Thanks.

**Comment by emrass** [comment]
@camargo Could you post the relevant part of your webpack.config and the error message you get in the console? I'll have a look at it to see if there are any similarities to my case.

**Comment by camargo** [comment]
@emrass The console is giving: `Uncaught TypeError: Cannot set property 'true' of undefined`. It is the same issue you discussed in this thread. It is also being discussed here: https://github.com/web-animations/web-animations-js/issues/45.

**Comment by emrass** [comment]
@camargo If I understand this correctly, you are having this issue for web-animations Polyfill? One way to deal with this would be to exclude it from your bundle. This might also be better for performance of your site, because your users might already have web-animations cached in their browsers, so it can be served from cache (not possible when it is included in your bundle).

Just remove any references to web-animations from any source files included in your bundle. Then add the reference to web-animations to a `<script>` tag in your index.html.

**Comment by camargo** [comment]
@emrass This worked like a charm. Thank you for your help.
