### ISSUE TITLE
How to use lib when importing in index.html with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by BorntraegerMarc** [aruntk/wc-loader#18]
Hi guys
Short question: I have an `index.html` that imports my web components with html imports. Like: `<link rel="import" href="bower_components/app-layout/app-layout.html">`
Also I am working in an angular project so my html webpack config looks like this:
```
            {
                test: /\.html$/,
                loader: 'html-loader'
            },
```

And I use `HtmlWebpackPlugin` to import the index.html, like this:
```
        new HtmlWebpackPlugin({
            template: 'index.html'
        })
```

How should I include the `wc-loader` in this setup?

**Comment by aruntk** [comment]
@BorntraegerMarc You'll have to ignore all other files except the desired file

```js
{
  test: /\.html$/,
  loader: 'html-loader',
  include: [
    path.resolve(__dirname, './index.html'),
  ],
},
{
  test: /\.html$/,  
  loader: 'wc-loader'
}
```
