### ISSUE TITLE
Externally hosted web components?

### ISSUE THREAD

**Issue by rchrd2** [aruntk/wc-loader#21]
Does this work with externally hosted web components? 

For example, would this externally hosted hello-world component be packaged?
```
<html>
  <link ref="import" href="https://example.com/components/hello-world.html">
</html>
```

I did a test, and it seems, like it was not packaged by default. 

What would it take to make this work?

**Comment by aruntk** [comment]
@rchrd2 wc-loader leaves external link as it is (from version 1.1.5). See this demo https://github.com/aruntk/polymer-webpack-demo/tree/external-link

link to external element -> https://github.com/aruntk/polymer-webpack-demo/blob/external-link/src/components/example-app.html#L13

Issue can be related to any of the following

- its `rel="import"` not `ref="import"`

- CORS not enabled.

**Comment by aruntk** [comment]
@rchrd2 Closing the issue.
