### ISSUE TITLE
Child combinator in CSS is replaced with &gt;

### ISSUE THREAD

**Issue by 4esnog** [aruntk/wc-loader#22]
I'm using styles inside of `<template>` via `<link>`:
```
<template>
	<link rel="stylesheet" href="./tags-select.css" />
	...
</template>
```

This `<link>` is being replaced with `<style>` tag, which contains styles from my file.

As I can see, the issue is that `parse5.serialize()` replaces all css child combinators (.parent **>** .child) with `&gt;` (.parent **\&gt;** .child).
Obviously, it breaks my styles.

**Comment by aruntk** [comment]
@4esnog Sorry but I'm not able to reproduce the issue. Check https://github.com/aruntk/polymer-webpack-demo/blob/master/src/components/example-app.html#L20 https://github.com/aruntk/polymer-webpack-demo/blob/master/src/components/example-app.css#L4 . Works as desired.

afaik parse5 does not change style/script. Could you please share your webpack config?

**Comment by 4esnog** [comment]
I've tried to play with parse5 in node repl, and here is the result:
![screen shot 2017-07-19 at 16 22 42](https://user-images.githubusercontent.com/11892253/28368867-8c20d160-6c9e-11e7-870a-10ff190ca90e.png)

The same stucture (style > \#text > my minified css) is generated by [processCssImport](https://github.com/aruntk/wc-loader/blob/master/src/index.js#L256)

UPD:
Found something interesting
![screen shot 2017-07-19 at 17 03 45](https://user-images.githubusercontent.com/11892253/28371039-8661a1b8-6ca4-11e7-81ab-65a7aa0ef575.png)
Seems like if `#text` node has no correct `parentNode` property, parse5 can't understand that this `#text` is actually contains styles

**Comment by aruntk** [comment]
@4esnog [Serialize](http://inikulin.github.io/parse5/globals.html#serialize) method is to serialize a node. Use 
[parseFragment method](http://inikulin.github.io/parse5/globals.html#parsefragment) if you are dealing with fragments

**Comment by 4esnog** [comment]
@aruntk I've added [here](https://github.com/aruntk/wc-loader/blob/master/src/index.js#L263) the next line: `parentNode: child` and it solved my problem.

**Comment by aruntk** [comment]
@4esnog published to npm. Use v1.1.7

**Comment by 4esnog** [comment]
@aruntk Thanks :)
