### ISSUE TITLE
Loader fails?

### ISSUE THREAD

**Issue by drager** [aruntk/wc-loader#28]
I have an `app.html` file which contains the following code: ```<link rel="import" href="../bower_components/paper-button/paper-button.html">``` and I have `import './app.html';` in my `index.js`. This however results in:

```src/app.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <link rel="import" href="../bower_components/paper-button/paper-button.html">
```

This is my webpack config: https://gist.github.com/drager/fa08ec7d252f54124b0880dac779b6ca

**Comment by aruntk** [comment]
@drager Sorry for the delayed reply. Could you share your package.json as well? I'm not able to reproduce the issue using https://github.com/aruntk/polymer-webpack-demo

**Comment by drager** [comment]
@aruntk: No problem, I resolved the issue. The problem was caused because Webpack didn't pick up my configuration file (which wasn't wc-loaders fault). So, now it works when it is picked it up.
