### ISSUE TITLE
Cannot resolve module 'wc'

### ISSUE THREAD

**Issue by JacobSoderblom** [aruntk/wc-loader#4]
I'm trying to use your loader but it wont work, probably something I have done. 😄 

```
Error in   Error: Child compilation failed:
  Module not found: Error: Cannot resolve module 'wc' in /private/var/www/path/to/components:
```

In my index.html i have the link tags that imports the web components
```
<link rel="import" href="../xcomp/components/xc-blanks.html" />
```

**Comment by aruntk** [comment]
@JacobSoderblom Did you install wc-loader? npm install --save-dev wc-loader

**Comment by JacobSoderblom** [comment]
@aruntk yes I did.

**Comment by aruntk** [comment]
@JacobSoderblom  could you try the demo and check if it is working?https://github.com/aruntk/polymer-webpack-demo

**Comment by JacobSoderblom** [comment]
@aruntk The demo seems to work just fine, but it's using polymer and I'm using native web components.

I'll start to compare my project with the demo project and try to see what's going wrong.

**Comment by aruntk** [comment]
> but it's using polymer and I'm using native web components.

@JacobSoderblom I dont think this has anything to do with the issue. It seems to be a module resolving issue.

**Comment by aruntk** [comment]
@JacobSoderblom Any update?

**Comment by JacobSoderblom** [comment]
@aruntk No it should not be a problem that I use native web components and the test polymer.

Nothing yet I'm afraid, did not have the time yesterday to look into it that much. Hopefully I'll have the time to day!

**Comment by JacobSoderblom** [comment]
@aruntk I tried to create a new project that has the same config as my other project, but I could not reproduce it. So it must be something in my project that's wrong.

I'll close this issue.

**Comment by aruntk** [comment]
@JacobSoderblom Okay. Glad to know the issue isn't occurring anymore. Thanks for checking out the project BTW. :)
