### ISSUE TITLE
Exclude img files?

### ISSUE THREAD

**Issue by MichaelFBA** [aruntk/wc-loader#6]
Is it possible to exclude img files?

This is in my webpack 2 config

```
module: {
        rules: [{
            test: /\.html$/, 
            use: ['wc-loader'],
            exclude: /(png|jpg|gif|svg)/,
        }, {
            test: /\.js$/,
            exclude: /(node_modules|scripts)/,
            use: [{
                loader: 'babel-loader',
                options: {
                    presets: ['es2015']
                }
            }],
        }, {
            test: /\.(sass|scss)$/,
            use: [
                'style-loader',
                'css-loader',
                'sass-loader',
            ]
        }]
    }
```

**Comment by aruntk** [comment]
I'm not completely sure what your requirement is. But,

```js
test: /\.html$/, 
use: ['wc-loader'],
```

Here only files with extension `.html` are processed by wc-loader. And code `exclude: /(png|jpg|gif|svg)/, ` excludes files and folders with name containing any of the given substrings (png|jpg|gif|svg).

If you want images to be shown use

```js {
      test: /\.(png|jpg|gif|svg)$/, // handles assets. eg <img src="path.png">
      loader: 'file',
      query: {
        name: '[name].[ext]?[hash]'
      }
    },
```

**Comment by MichaelFBA** [comment]
Yep, but if the `.html` files include a reference to an `<img src="/images/haus-logo.svg"` an error is thrown.

```
ERROR in ./lib/components/home-page/home-page.html
Module not found: Error: Can't resolve './images/haus-logo.svg' in '/Users/michaelbell/Documents/haus/lib/components/home-page'
```

I noticed you are using the `file-loader` plugin in your example repo. But I would prefer not to use that.

**Comment by aruntk** [comment]
Absolute and remote urls should not have been processed. There seems to be a bug in this which I'll fix now.

This feature is a newly added one. I've not added query options.If you want to skip relative path image urls you'll have to wait some time. I'm working on that. For now you can either use the latest 0.x version or wait till I add or this feature(which will take some time). Feel free to add pr's if you want to add this feature yourself. :).

**Comment by aruntk** [comment]
@MichaelFBA Please check now. absolute urls and remote urls are excluded by default.

**Comment by MichaelFBA** [comment]
👍  Nice one. Thanks mate

**Comment by aruntk** [comment]
@MichaelFBA Welcome mate. And thanks for trying the package and raising the issue. :) Regarding css, currently css paths are also being handled by wc-loader itself. It wont pass that to css-loader. (This will be removed in the future and you'll be able to use css-loader).

**Comment by MichaelFBA** [comment]
Ach so, just noticed that :)

**Comment by aruntk** [comment]
@MichaelFBA My objective is to create a common method to handle style tags and css file imports. Thats why I kept it like this for now.

**Comment by aruntk** [comment]
@MichaelFBA This is a simpler modular version of wc-loader. https://github.com/aruntk/link-loader

Demo - https://github.com/aruntk/link-loader-demo

Check this out.
